from pytrends.request import TrendReq
import pandas as pd
import time

# Replace this with your cleaned list
terms_cleaned = [
    "/m/01b_21",
    "/m/01c751",
    "/m/028tns",
    "/m/03t8j0",
    "/m/0416v7",
    "/m/05s5v6",
    "/m/0683jy",
    "/m/06n3pj",
    "/m/06p_bp",
    "/m/087cyy",
    "/m/08pr_0",
    "/m/0b2cnj",
    "/m/0b76bty",
    "/m/0cjf0",
    "/m/0g9pc",
    "/m/0gxb2",
    "/m/0j5fv",
    "/m/0n073",
    "acute bronchitis",
    "avian flu",
    "best cold medicine",
    "best cough medicine",
    "best medicine for cold",
    "body temperature",
    "braun thermoscan",
    "break a fever",
    "bronchitis",
    "cdc",
    "chest cold",
    "cold and cough",
    "cold flu",
    "cold flu symptoms",
    "cold symptoms",
    "congestion medicine",
    "cough and fever",
    "cough and sore throat",
    "cure flu",
    "dangerous fever",
    "dry cough",
    "ear thermometer",
    "epidemic",
    "expectorant",
    "fever",
    "fever and chills",
    "fever flu symptoms",
    "fever reducer",
    "fever symptoms",
    "fever with flu",
    "flu a symptoms",
    "flu and fever",
    "flu care",
    "flu children",
    "flu cough",
    "flu headache",
    "flu incubation",
    "flu like symptoms",
    "flu medicine",
    "flu remedies",
    "flu stomach pain",
    "flu test",
    "flu texas",
    "flu treatment",
    "flu virus",
    "food poisoning",
    "food poisoning symptoms",
    "h1n1",
    "high fever",
    "how long contagious",
    "how long does flu last",
    "how long does the flu last",
    "human temperature",
    "i have the flu",
    "incubation period",
    "influenza symptoms",
    "low body",
    "nausea",
    "normal body",
    "normal body temperature",
    "oscillococcinum",
    "pandemic",
    "period fever",
    "period flu",
    "pneumonia",
    "pneumonia symptoms",
    "reduce fever",
    "robitussin",
    "rsv symptoms",
    "signs of flu",
    "sinus",
    "sinus infections",
    "sinus medicine",
    "spanish flu",
    "stomach flu",
    "stomach flu diarrhea",
    "stomach flu symptoms",
    "stomach flu virus",
    "stomach virus",
    "stomach virus symptoms",
    "strep",
    "strep throat",
    "symptoms of a cold",
    "symptoms of bronchitis",
    "symptoms of cold",
    "symptoms of fever",
    "symptoms of pneumonia",
    "symptoms of stomach flu",
    "symptoms of the flu",
    "taking temperature",
    "tessalon",
    "the flu",
    "the flu symptoms",
    "the flu virus",
    "the flue",
    "thermoscan",
    "treat flu",
    "tussin",
    "tussionex",
    "tylenol extra strength",
    "upper respiratory",
    "vomiting",
    "walking pneumonia",
    "what is a fever",
    "what is the flu",
    "covid",
    "covid deaths",
    "covid incubation period",
    "covid vs flu vs cold",
    "incubation period for covid",
    "medicine for covid",
    "spanish flu vs covid",
    "1918 spanish flu",
    "cold vs flu vs allergies",
    "covid 19",
    "h1n1 avian flu",
    "spanish flu death toll",
    "spanish flu deaths",
    "spanish flu epidemic",
    "spanish flu h1n1",
    "spanish flu of 1918",
    "spanish flu origin",
    "spanish flu pandemic",
    "spanish flu symptoms",
    "spanish flu virus",
    "spanish flu ww1",
    "spanish flue",
    "the spanish flu",
    "the spanish flu pandemic",
    "was the spanish flu a pandemic",
    "when was spanish flu",
    "avian bird flu",
    "avian flu h5n1",
    "avian flu symptoms",
    "avian flu vaccine",
    "bird flu pandemic",
    "bird flu symptoms",
    "bird flu vaccine",
    "bird flu virus",
    "cdc avian flu",
    "cdc bird flu",
    "h5n1 bird flu",
    "human bird flu",
    "new bird flu",
    "symptoms of bird flu",
    "what is bird flu",
    "avian flu news",
    "avian flu outbreak",
    "bird flu outbreak",
    "covid vs flu vs cold chart",
    "flu symptoms vs common cold",
    "flu virus incubation period",
    "flu vs common cold",
    "head cold vs flu",
    "symptoms of a cold vs flu",
    "tylenol cold and flu while pregnant",
    "2024 flu strain",
    "cold and flu medicine for kids",
    "is the spanish flu influenza",
    "avian flu california",
    "avian flu symptoms in humans",
    "avian influenza symptoms",
    "best cold and flu medicine for adults",
    "best cough medicine for flu",
    "best medicine for flu and cough",
    "best over the counter cold and flu medicine",
    "children's mucinex cold and flu",
    "cold and flu medicine for adults",
    "current flu symptoms 2024",
    "cvs cold and flu medicine",
    "flu gestation period",
    "flu medicine for kids",
    "flu no cough",
    "flu reports",
    "flu symptoms 2024 adults",
    "human avian flu",
    "influenza b symptoms in adults",
    "mucinex cold and flu ingredients",
    "mucinex cold and flu liquid",
    "mucinex fast max cold flu and sore throat",
    "mucinex fast-max cold and flu",
    "mucinex nightshift cold and flu",
    "mucinex pills",
    "new avian flu",
    "new flu symptoms 2024",
    "nighttime cold and flu medicine",
    "period flu reddit",
    "period flu sore throat",
    "symptoms of bird flu in humans",
    "symptoms of flu type a",
    "symptoms of the bird flu",
    "the bird flu symptoms",
    "tylenol cold and flu day and night",
    "tylenol cold and flu pills",
    "tylenol cold and flu pregnancy",
    "tylenol cold and flu severe liquid",
    "tylenol cold and flu severe night",
    "tylenol cold and flu walmart",
    "tylenol nighttime cold and flu",
    "tylenol severe cold and flu liquid",
    "type a flu treatment",
    "walgreens cold and flu",
    "walgreens cold and flu medicine",
    "cold symptoms 2024",
    "flu 2024",
    "flu a symptoms 2024",
    "flu b symptoms 2024",
    "flu season 2024",
    "norovirus 2024",
    "norovirus 2024 symptoms",
    "stomach flu 2024",
    "stomach flu symptoms 2024",
    "symptoms of covid 2024",
    "symptoms of flu 2024",
    "symptoms of the flu 2024",
    "avian flu 2024",
    "avian flu in milk",
    "bird flu 2024 symptoms",
    "bird flu humans",
    "bird flu in humans",
    "bird flu in milk",
    "bird flu milk",
    "bird flu symptoms humans",
    "bird flu symptoms in humans",
    "bird flu to humans",
    "bird flu vs avian flu",
    "flu outbreak 2024",
    "avian flu humans",
    "avian flu in chickens",
    "avian flu in humans",
    "avian flu michigan",
    "avian flu symptoms in chickens",
    "bird flu avian influenza",
    "bird flu texas",
    "flu type a incubation period",
    "symptoms of avian flu",
    "what is avian flu",
    "advil cold and flu",
    "allergies vs cold",
    "best cold and flu medicine",
    "best cold flu medicine",
    "best medicine for cold and flu",
    "best medicine for flu and cold",
    "body aches no fever",
    "children's tylenol",
    "cold and flu alka seltzer",
    "cold flu medicine",
    "coricidin cold and flu",
    "cough and cold medicine",
    "cough and flu medicine",
    "dayquil cold and flu",
    "dayquil severe cold and flu",
    "daytime cold and flu",
    "equate cold and flu",
    "fever breaks",
    "flu and cough medicine",
    "flu cough medicine",
    "how to break a fever",
    "how to bring a fever down",
    "is stomach flu going around",
    "is the flu going around",
    "kids cold and flu",
    "kids flu medicine",
    "medicine for cold and flu",
    "medicine for fever",
    "mucinex cold and flu",
    "mucinex cough medicine",
    "mucinex fast max",
    "mucinex max cold and flu",
    "mucinex night shift",
    "mucinex sinus max",
    "mucinex sore throat",
    "nighttime cold and flu",
    "nyquil cold and flu",
    "nyquil cold and flu severe",
    "nyquil severe cold and flu",
    "reduce a fever",
    "severe cold and flu",
    "severe cold and flu medicine",
    "severe flu medicine",
    "stomach flu going around",
    "symptoms of stomach bug",
    "theraflu cold and flu",
    "tylenol cold and flu",
    "tylenol cold flu",
    "tylenol cough and cold",
    "tylenol for cold and flu",
    "tylenol severe cold and flu",
    "type a vs type b",
    "vicks cold and flu",
    "best flu medicine for adults",
    "children's tylenol cold and flu",
    "cold and flu medicine liquid",
    "flu a symptoms 2023",
    "flu b symptoms 2023",
    "flu medicine for adults",
    "flu symptoms 2023",
    "kids cold and flu medicine",
    "mucinex cold and flu dosage",
    "mucinex cold and flu medicine",
    "mucinex cold flu and sore throat",
    "mucinex severe cold and flu",
    "over the counter flu test",
    "symptoms of rsv",
    "tylenol cold and flu breastfeeding",
    "tylenol cold and flu ingredients",
    "tylenol cold and flu kids",
    "tylenol cold and flu night",
    "walgreens tylenol cold and flu",
    "alka seltzer cold and cough",
    "cold vs sinus infection",
    "flu vs stomach flu",
    "food poisoning vs stomach flu",
    "how long does stomach flu last",
    "incubation period cold",
    "incubation period for cold",
    "incubation period for stomach flu",
    "incubation period stomach flu",
    "is stomach flu contagious",
    "norovirus stomach flu",
    "painful cough",
    "stomach flu contagious",
    "stomach flu fever",
    "stomach flu medicine",
    "stomach flu treatment",
    "stomach flu with fever",
    "symptoms of the stomach flu",
    "tylenol cold and sinus",
    "what is stomach flu",
    "best over the counter flu medicine",
    "cold and flu symptoms",
    "cold symptoms vs flu symptoms",
    "cold vs flu symptoms",
    "cure the flu",
    "do i have the flu",
    "early flu symptoms",
    "fight the flu",
    "flu complications",
    "flu contagious period",
    "flu duration",
    "flu germs",
    "flu in children",
    "flu incubation period",
    "flu length",
    "flu medicine over the counter",
    "flu no fever",
    "flu recovery",
    "flu remedy",
    "flu report",
    "flu symptoms cough",
    "flu symptoms treatment",
    "flu symptoms without fever",
    "flu treatments",
    "get over the flu",
    "get rid of the flu",
    "how is the flu spread",
    "how to get rid of the flu",
    "how to treat flu",
    "how to treat the flu",
    "incubation period flu a",
    "incubation period for flu",
    "incubation period for flu a",
    "incubation period for the flu",
    "incubation period of flu",
    "incubation period of the flu",
    "influenza incubation",
    "influenza incubation period",
    "is influenza the flu",
    "is the flu a virus",
    "over the counter flu",
    "over the counter flu medicine",
    "over the counter medicine for flu",
    "period flu symptoms",
    "remedies for flu",
    "remedies for the flu",
    "respiratory flu",
    "signs of the flu",
    "symptoms for the flu",
    "treat the flu",
    "treating flu",
    "treating the flu",
    "treatment for flu",
    "treatment for the flu",
    "what are the symptoms of the flu",
    "what is period flu",
    "what to do if you have the flu",
    "whats the flu",
    "difference in flu type a and b",
    "flu b incubation period",
    "flu b symptoms",
    "flu b treatment",
    "flu type a vs b",
    "flu type a vs type b",
    "flu type b symptoms",
    "flu type b vs a",
    "influenza b symptoms",
    "symptoms of flu b",
    "symptoms of flu type b",
    "symptoms of influenza b",
    "the flu vs a cold",
    "type a and b flu",
    "type a flu vs type b flu",
    "type b flu symptoms",
    "what is flu b",
    "what is flu b symptoms",
    "what is type a and b flu",
    "influenza a vs b symptoms",
    "medicine for flu and cough",
    "stomach flu vs stomach bug",
    "/m/09gh4jl",
    "best flu medicine",
    "best medicine for flu",
    "best medicine for flu symptoms",
    "best medicine for the flu",
    "best over the counter medicine for flu",
    "cough after flu",
    "cough from flu",
    "cough with flu",
    "dry cough flu",
    "exposed to flu",
    "fever vs flu",
    "fever with the flu",
    "flu a and b symptoms",
    "flu a contagious",
    "flu a vs b symptoms",
    "flu a vs flu b",
    "flu a vs flu b symptoms",
    "flu and cough",
    "flu but no fever",
    "flu how long are you contagious",
    "flu lasts",
    "flu medicine tamiflu",
    "flu relief",
    "flu symptoms medicine",
    "flu type a symptoms",
    "flu vs fever",
    "flu with no fever",
    "flu without fever",
    "having the flu",
    "how long is flu contagious",
    "how long is the flu",
    "how long is the flu contagious",
    "how to treat the flu at home",
    "influenza a and b",
    "influenza a symptoms",
    "influenza contagious",
    "influenza treatment",
    "medicine for flu",
    "medicine for flu symptoms",
    "medicine for the flu",
    "rapid flu",
    "stomach bug or flu",
    "symptoms of influenza",
    "symptoms of influenza a",
    "tamiflu medicine",
    "test for the flu",
    "the flu type a",
    "type a flu",
    "type a flu contagious",
    "type a flu symptoms",
    "what is flu type a",
    "current flu symptoms",
    "flu type a treatment",
    "how long am i contagious with the flu",
    "type a influenza symptoms",
]
for term in terms_cleaned:
    if term.startswith("/m/"):
        print(f"Term '{term}' is a Google Knowledge Graph ID, skipping.")
        terms_cleaned.remove(term)

# Group terms into batches of 5
term_batches = [terms_cleaned[i:i + 5] for i in range(0, len(terms_cleaned), 5)]

# Initialize pytrends
pytrends = TrendReq(hl='en-US', tz=360)
all_data = pd.DataFrame()

# Query each batch
for i, batch in enumerate(term_batches):
    try:
        pytrends.build_payload(batch, timeframe='2022-01-01 2024-12-31', geo='US')
        df = pytrends.interest_over_time().drop(columns=['isPartial'])

        if all_data.empty:
            all_data = df
        else:
            all_data = all_data.join(df, how='outer')

        print(f"Batch {i+1} completed: {batch}")
        time.sleep(2)
    except Exception as e:
        print(f"Batch {i+1} failed: {e}")

# Save to CSV
all_data.to_csv("ShiHaoYang/Data/trends_us_data.csv")
print("Saved to trends_data.csv")